### ISSUE TITLE
Update the plugin to work with the next release (3.4.0)

### ISSUE THREAD

**Issue by jonasraoni** [pkp/defaultTranslation#9]
At this moment the plugin is using a non-existent hook and depending on code that doesn't exist anymore.
It must be updated to work with the current code at the /main branch of OJS/OPS/OMP.

PR:
- https://github.com/pkp/defaultTranslation/pull/10

**Comment by jonasraoni** [comment]
Hi @asmecher, here's the PR to address the localization updates.

**Comment by jonasraoni** [comment]
Is it useful to add an option to fallback to a similar language before English? Then a missing translation for `pt_BR`, could attempt to find a match in `pt_PT`, before moving to `en_US`.

**Comment by jonasraoni** [comment]
Also, I've merged this PR into mine one: https://github.com/pkp/defaultTranslation/pull/8, so you can close it =]

**Comment by asmecher** [comment]
Thanks!

**Comment by jonasraoni** [comment]
@asmecher You forgot to merge the PR (or perhaps misunderstood my previous message) 😁

**Comment by asmecher** [comment]
OK, gotcha -- closed that PR and re-opened this issue.

**Comment by asmecher** [comment]
> Is it useful to add an option to fallback to a similar language before English? Then a missing translation for pt_BR, could attempt to find a match in pt_PT, before moving to en_US.

I haven't heard a specific call for this, but I could see it being useful for dialects that don't differ much from existing widely-used translations. If it's not much code to add, yes, please do.

**Comment by jonasraoni** [comment]
@asmecher I just addressed the comment above, so this PR is ready as well.
